language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - git config --global user.name "TravisCI"
install:
  - cpanm --skip-satisfied -n Devel::Cover::Report::Coveralls CPAN::Meta Dist::Zilla
  - dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
  - dzil listdeps | grep -vP '[^\w:]' | cpanm --verbose
script:
  - dzil smoke --release --author